name: Sync Fork

on:
  schedule:
    # 每天凌晨2点执行同步操作
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/ACL4SSR/ACL4SSR

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync all branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | sed 's/upstream\///'); do
            if [ "$branch" != "HEAD" ]; then
              git checkout -B $branch upstream/$branch
              git push -f origin $branch
            fi
          done    